susan: susan.c Makefile
	gcc -static -O3 -o susan susan.c -lm -Wno-implicit-function-declaration -Wno-int-conversion -Wno-implicit-int -Wno-deprecated-non-prototype -Wno-unused-value -Wno-pointer-sign -Wno-literal-conversion

clean:
	rm -rf susan output*
